spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5434/payments
    username: saga
    password: saga
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        "[spring.json.value.default.type]": payment_service.event.InventoryReservedEvent
        "[spring.json.use.type.headers]": false
        "[spring.json.trusted.packages]": payment_service.event

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: 8082